core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('', include('login.urls')),
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('user/', include('user.urls')),
    path('topsis/', include('topsis.urls')),
    
]

topsis/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("input/", views.input, name="input"),
    path("analyze/", views.analysis, name="analyze"),
    path("analyze_wakil/", views.analysis_wakil, name="analyze_wakil"),
    path("analyze/<int:year>/", views.analysis, name="analyze_year"),  # Ubah path untuk menerima parameter tahun
    path("analyze_wakil/", views.analysis_wakil, name="analyze_wakil"),
    path("<int:year>/", views.index, name="index_year"),  # Add a path for handling the year parameter
    path('edit/<int:id>',views.edit, name='edit'),
    path('update/<int:id>',views.update, name='topsis.update'),
    path('delete/<int:id>',views.delete, name='topsis.delete'),
]

topsis/models.py
from django.db import models
from datetime import datetime
# Create your models here.


class Data(models.Model):
    """Model definition for Data."""

    class SuratKeteranganTidakMampu(models.IntegerChoices):
        K1 = 1, "Tidak Ada"
        K2 = 2, "Ada"

    class KondisiRumah(models.IntegerChoices):
        KR1 = 1, "Batu Bata Lantai Keramik"
        KR2 = 2, "Batu Bata Lantai Semen"

    class KeaktifanEkstrakurikuler(models.IntegerChoices):
        P1 = 1, "Tidak Aktif"
        P2 = 2, "Jarang"  # Nilai duplikat
        P3 = 3, "Aktif"

    class Penghasilan (models.IntegerChoices):
        PE1 = 1, "> 1.500.000"
        PE2 = 2, ">= 1.500.000 - <= 1.000.000"
        PE3 = 3, "<= 900.000 - >= 500.000"
        PE4 = 4, "Tidak Berpenghasilan"

    class Tanggungan (models.IntegerChoices):
        T1 = 1, "Satu"
        T2 = 2, "Dua"
        T3 = 3, "Tiga"
        T4 = 4, "Empat"

    class Keterangan (models.IntegerChoices):
        Y1 = 1, "Penghasilan OrangTua"
        Y2 = 2, "Yatim"

    nama = models.CharField(
        null=False,
        max_length=50,
        verbose_name="Nama",
    )
 
    surat_keterangan_tidak_mampu = models.IntegerField(
        choices=SuratKeteranganTidakMampu.choices,
        verbose_name="Surat Keterangan Tidak Mampu",
        default=SuratKeteranganTidakMampu.K1  #default value
    )
    kondisi_rumah = models.IntegerField(
        choices=KondisiRumah.choices,
        verbose_name="Kondisi Rumah",
    )
    keaktifan_ekstrakurikuler = models.IntegerField(
        choices=KeaktifanEkstrakurikuler.choices,
        verbose_name="Keaktifan Ekstrakurikuler",
        default=KeaktifanEkstrakurikuler.P1
    )
    penghasilan = models.IntegerField(
        choices=Penghasilan.choices,
        verbose_name="Penghasilan OrangTua",
    )
    tanggungan = models.IntegerField(
        choices=Tanggungan.choices,
        verbose_name="Tanggungan OrangTua",
    )
    keterangan = models.IntegerField(
        choices=Keterangan.choices,
        verbose_name="Keterangan",
    )
    tahun = models.IntegerField(
        verbose_name="Tahun",
        help_text="Tahun data diinput",
        default=datetime.now().year
    )

    class Meta:
        """Meta definition for Data."""

        verbose_name = "Data"
        verbose_name_plural = "Data"

    # def __str__(self):
    #     return self.nama
    def __str__(self):
        return f"{self.nama} -  {self.tahun}" 

topsis/forms.py
from django import forms

from topsis.models import Data

class DataForm(forms.ModelForm):
    class Meta:
        model = Data
        fields = '__all__'

class YearForm(forms.Form):
    year = forms.IntegerField(label='Enter Year')

topsis/views.py
import numpy as np

from django.http import HttpResponseRedirect
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse

from topsis.forms import DataForm
from topsis.models import Data
from topsis.topsis import Topsis
from datetime import datetime

# def index(request, year=None):
#     if year is None:
#         year = datetime.now().year
#     else:
#         year = int(year)
    
#     data = Data.objects.filter(tahun=year)
    
#     field_names = [f.verbose_name for f in Data._meta.get_fields()]
#     weights = [5, 3, 3, 3, 4, 4]
#     criterias = np.array([True, True, True, True, True, True])
#     arr = []
#     for d in data:
#         arr.append(
#             [
#                 [d.kondisi_ekonomi],
#                 [d.kondisi_rumah],
#                 [d.pekerjaan],
#                 [d.penghasilan],
#                 [d.tanggungan],
#                 [d.keterangan],
#             ]
#         )

#     evaluation_matrix = np.array(arr)
#     t = Topsis(evaluation_matrix, weights, criterias)
#     t.calc()

#     for i, d in enumerate(data):
#         d.best_distance = t.best_distance[i]
#         d.worst_distance = t.worst_distance[i]
#         d.worst_similarity = t.worst_similarity[i]
#         d.worst_similarity_rank = t.rank_to_worst_similarity()[i]
#         d.best_similarity = t.best_similarity[i]
#         d.best_similarity_rank = t.rank_to_best_similarity()[i]
#         d.weighted_normalized = t.weighted_normalized[i]
#         #1 
#         d.evaluation_matrix = t.evaluation_matrix[i]
#         d.normalized_decision = t.normalized_decision[i]  # Normalisation matrix

#         # d.ci_plus = t.calculate_ci_plus()[i]
    
#     available_years = Data.objects.values_list('tahun', flat=True).distinct()

#     context = {
#         "data": data,
#         "field_names": field_names,
#         "selected_year": int(year),
#         "available_years": available_years,
#     }

#     return render(request, "index.html", context)
def index(request):
    year = request.GET.get('year', None)
    
    if year is None:
        year = datetime.now().year
    else:
        year = int(year)
    
    data = Data.objects.filter(tahun=str(year))
    
    field_names = [f.verbose_name for f in Data._meta.get_fields()]
    weights = [5, 3, 3, 3, 4, 4]
    criterias = np.array([True, True, True, True, True, True])
    arr = []
    for d in data:
        arr.append(
            [
                [d.surat_keterangan_tidak_mampu],
                [d.kondisi_rumah],
                [d.keaktifan_ekstrakurikuler],
                [d.penghasilan],
                [d.tanggungan],
                [d.keterangan],
            ]
        )

    evaluation_matrix = np.array(arr)
    t = Topsis(evaluation_matrix, weights, criterias)
    t.calc()

    for i, d in enumerate(data):
        d.best_distance = t.best_distance[i]
        d.worst_distance = t.worst_distance[i]
        d.worst_similarity = t.worst_similarity[i]
        d.worst_similarity_rank = t.rank_to_worst_similarity()[i]
        d.best_similarity = t.best_similarity[i]
        d.best_similarity_rank = t.rank_to_best_similarity()[i]
        d.weighted_normalized = t.weighted_normalized[i]
        #1 
        d.evaluation_matrix = t.evaluation_matrix[i]
        d.normalized_decision = t.normalized_decision[i]  # Normalisation matrix

        # d.ci_plus = t.calculate_ci_plus()[i]
    
    available_years = Data.objects.values_list('tahun', flat=True).distinct()

    context = {
        "data": data,
        "field_names": field_names,
        "selected_year": int(year),
        "available_years": available_years,
    }

    return render(request, "index.html", context)

def edit(request, id):
    category = get_object_or_404(Data, id=id)
    form = DataForm(instance=category)
    context = {
        'form': form,
        'category': category,  # Sertakan category dalam konteks
    }
    return render(request, 'topsis_edit.html', context)



# Perbaikan pada fungsi update
def update(request, id):
    category = get_object_or_404(Data, id=id)
    if request.method == 'POST':
        form = DataForm(request.POST, instance=category)  # Gunakan instance=category untuk mengisi form dengan data yang sudah ada
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('index'))  # Redirect ke halaman utama setelah berhasil diperbarui
    else:
        form = DataForm(instance=category)  # Gunakan instance=category untuk mengisi form dengan data yang sudah ada

    context = {
        'form': form,  # Gunakan form yang sudah diisi dengan data objek category
    }
    return render(request, 'topsis_edit.html', context)


# Perbaikan pada fungsi delete

def delete (request,id):
    category = get_object_or_404(Data,id=id)
    category.delete()
    return redirect('index')
# def analysis(request):
#     data = Data.objects.all()
#     weights = [5, 3, 3, 3, 4, 4]
#     criteria = np.array([True, True, True, True, True, True])
#     arr = []
#     for d in data:
#         arr.append(
#             [
#                 [d.kondisi_ekonomi],
#                 [d.kondisi_rumah],
#                 [d.pekerjaan],
#                 [d.penghasilan],
#                 [d.tanggungan],
#                 [d.keterangan],

#             ]
#         )

#     evaluation_matrix = np.array(arr)
#     t = Topsis(evaluation_matrix, weights, criteria)
#     t.calc()

#     for i, d in enumerate(data):
#         d.best_distance = t.best_distance[i]
#         d.worst_distance = t.worst_distance[i]
#         d.worst_similarity = t.worst_similarity[i]
#         d.worst_similarity_rank = t.rank_to_worst_similarity()[i]
#         d.best_similarity = t.best_similarity[i]
#         d.best_similarity_rank = t.rank_to_best_similarity()[i]
#         d.weighted_normalized = t.weighted_normalized[i]
        
#         #1 
#         d.evaluation_matrix = t.evaluation_matrix[i]
#         d.normalized_decision = t.normalized_decision[i]
#         # d.ci_plus = t.calculate_ci_plus()[i]

#     context = {"data": data}

#     return render(request, "analysis.html", context)

# def analysis_wakil(request):
#     data = Data.objects.all()
#     weights = [5, 3, 3, 3, 4, 4]
#     criteria = np.array([True, True, True, True, True, True])
#     arr = []
#     for d in data:
#         arr.append(
#             [
#                 [d.kondisi_ekonomi],
#                 [d.kondisi_rumah],
#                 [d.pekerjaan],
#                 [d.penghasilan],
#                 [d.tanggungan],
#                 [d.keterangan],

#             ]
#         )

#     evaluation_matrix = np.array(arr)
#     t = Topsis(evaluation_matrix, weights, criteria)
#     t.calc()

#     for i, d in enumerate(data):
#         d.best_distance = t.best_distance[i]
#         d.worst_distance = t.worst_distance[i]
#         d.worst_similarity = t.worst_similarity[i]
#         d.worst_similarity_rank = t.rank_to_worst_similarity()[i]
#         d.best_similarity = t.best_similarity[i]
#         d.best_similarity_rank = t.rank_to_best_similarity()[i]
#         d.weighted_normalized = t.weighted_normalized[i]
        
#         #1 
#         d.evaluation_matrix = t.evaluation_matrix[i]
#         d.normalized_decision = t.normalized_decision[i]
#         # d.ci_plus = t.calculate_ci_plus()[i]

#     context = {"data": data}

#     return render(request, "analysis_wakil.html", context)
# views.py

def analysis(request):
    selected_year = request.GET.get('year', None)

    if selected_year is None:
        selected_year = datetime.now().year
    else:
        selected_year = int(selected_year)

    data = Data.objects.filter(tahun=selected_year)
    
    weights = [5, 3, 3, 3, 4, 4]
    criteria = np.array([True, True, True, True, True, True])
    arr = []
    for d in data:
        arr.append(
            [
                [d.surat_keterangan_tidak_mampu],
                [d.kondisi_rumah],
                [d.keaktifan_ekstrakurikuler],
                [d.penghasilan],
                [d.tanggungan],
                [d.keterangan],
            ]
        )

    evaluation_matrix = np.array(arr)
    t = Topsis(evaluation_matrix, weights, criteria)
    t.calc()

    for i, d in enumerate(data):
        d.best_distance = t.best_distance[i]
        d.worst_distance = t.worst_distance[i]
        d.worst_similarity = t.worst_similarity[i]
        d.worst_similarity_rank = t.rank_to_worst_similarity()[i]
        d.best_similarity = t.best_similarity[i]
        d.best_similarity_rank = t.rank_to_best_similarity()[i]
        d.weighted_normalized = t.weighted_normalized[i]
        
        d.evaluation_matrix = t.evaluation_matrix[i]
        d.normalized_decision = t.normalized_decision[i]

    available_years = Data.objects.values_list('tahun', flat=True).distinct()

    context = {
        "data": data,
        "selected_year": int(selected_year),
        "available_years": available_years,
    }

    return render(request, "analysis.html", context)


# views.py

def analysis_wakil(request):
    selected_year = request.GET.get('year', None)

    if selected_year is None:
        selected_year = datetime.now().year
    else:
        selected_year = int(selected_year)

    data = Data.objects.filter(tahun=selected_year)
    
    weights = [5, 3, 3, 3, 4, 4]
    criteria = np.array([True, True, True, True, True, True])
    arr = []
    for d in data:
        arr.append(
            [
                [d.surat_keterangan_tidak_mampu],
                [d.kondisi_rumah],
                [d.keaktifan_ekstrakurikuler],
                [d.penghasilan],
                [d.tanggungan],
                [d.keterangan],
            ]
        )

    evaluation_matrix = np.array(arr)
    t = Topsis(evaluation_matrix, weights, criteria)
    t.calc()

    for i, d in enumerate(data):
        d.best_distance = t.best_distance[i]
        d.worst_distance = t.worst_distance[i]

topsis/templates/analysis.html
{% extends 'base.html' %}
{% block content %}

<form id="filterForm" method="GET" action="{% url 'analyze' %}">
    <!-- Pilihan tahun -->
    <select name="year" id="year">
        {% for available_year in available_years %}
            <option value="{{ available_year }}" {% if available_year == selected_year %}selected{% endif %}>{{ available_year }}</option>
        {% endfor %}
    </select>
    <button type="button" onclick="submitForm()">Filter</button>
</form>

<script>
    function submitForm() {
        document.getElementById("filterForm").submit();
    }
</script>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row d-flex justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Matriks</h6>
        </div>
    </div>
    
    <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Data Dalam Bentuk Matrik</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        {% for d in data %}
                            {{ d.evaluation_matrix}}<br>
                        {% endfor %}
                    </td>
                </tr>
            </tbody>
        </table>
        </div>
    </div>

    <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Normalisasi Matrix</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        {% for d in data %}
                            {{ d.normalized_decision}}<br>
                        {% endfor %}
                    </td>
                </tr>
            </tbody>
        </table>
        </div>
    </div>

    <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Matrik Terbobot</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                    <!-- cek terbobot -->
                        {% for d in data %}
                            {{ d.weighted_normalized }}<br>
                        {% endfor %}
                    </td>
                </tr>
            </tbody>
        </table>
        
        </div>
    </div>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row d-flex justify-content-between">
            Analisis data 
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table id="dataTable" class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                
                <!-- head -->
                <thead>
                    <tr>
                        <th>Nama</th>
                        <th>best_distance</th>
                        <th>worst_distance</th>
                        <th>worst_similarity</th>
                        <th>worst_similarity_rank</th>
                        <th>best_similarity</th>
                        <th>best_similarity_rank</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- row 1 -->
                    {% for d in data %}
                    <tr>
                        <th>{{ d.nama }}</th>
                        <td>{{ d.best_distance }}</td>
                        <td>{{ d.worst_distance }}</td>
                        <td>{{ d.worst_similarity }}</td>
                        <td>{{ d.worst_similarity_rank }}</td>
                        <td>{{ d.best_similarity }}</td>
                        <td>{{ d.best_similarity_rank }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row d-flex justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Top 3 and Bottom 3 Records</h6>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Top 3 - best_similarity_rank</th>
                </tr>
            </thead>
            <tbody>
                {% for d in data|dictsortreversed:"best_similarity_rank"|slice:":3" %}
                <tr>
                    <td>{{ d.nama }} - {{ d.best_similarity_rank }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <table class="table table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>Bottom 3 - worst_similarity_rank</th>
                </tr>
            </thead>
            <tbody>
                {% for d in data|dictsort:"worst_similarity_rank"|slice:":3" %}
                <tr>
                    <td>{{ d.nama }} - {{ d.worst_similarity_rank }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <table class="table table-bordered" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>RANK</th>
                </tr>
            </thead>
            <tbody>
                {% for d in data|dictsortreversed:"best_similarity_rank"|slice:":3" %}
                <tr>
                    <td>{{ d.nama }} - {{ d.best_similarity_rank }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        
        </div>
    </div>
</div>



{% endblock %}

topsis/templates/analysis_wakil.html
{% extends 'wakil.html' %}
{% load static %}
{% block content %}

<form id="filterForm" method="GET" action="{% url 'analyze_wakil' %}">
    <!-- Pilihan tahun -->
    <select name="year" id="year">
        {% for available_year in available_years %}
            <option value="{{ available_year }}" {% if available_year == selected_year %}selected{% endif %}>{{ available_year }}</option>
        {% endfor %}
    </select>
    <button type="button" onclick="submitForm()">Filter</button>
</form>

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row d-flex justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Hasil Analisis</h6>
            <button class="btn btn-primary" onclick="cetakTabel()">Cetak</button>
        </div>
    </div>
    
    <div class="card-body" id="printArea">
        <!-- ____________________________________________________________________________________________________________________________________________________________________ -->
        <!-- <strong>=========================================================================================================================================</strong> -->
        <hr style="border-top: 1.5px solid black;">
        <img src="{% static 'img/logo.png' %}" alt="Logo" style="float: left; max-width: 100px;">
        <img src="{% static 'img/Lambang_Kabupaten_Siak.png' %}" alt="Logo" style="float: right; max-width: 80px;">
        <strong style="display: block; margin: 0 auto; text-align: center; font-size:24px;">SURAT PERNYATAAN PENERIMA BEASISWA</strong>
        <strong style="display: block; margin: 0 auto; text-align: center; font-size:16px;">SMA NEGERI 3 TUALANG</strong>
        <p style="display: block; margin: 0 auto; text-align: center;">JL. AMD Pinang Sebatang Timur, Perawang, Kabupaten Siak</p><br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<p style="display: block; margin: 0 auto; text-align: center;">email: sman3tualang@gmail.com &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  nohp: 081266525522</p>
        <!-- <strong>=========================================================================================================================================</strong> -->
        <hr class="my-4" style="border-top: 1.5px solid black;">
        <!-- <hr class="border my-4"> -->
        <br>
        
        
        <p>
            Dengan hormat,
        </p>
        <p>
            Kami menyampaikan hasil analisis penerima Beasiswa Bantuan Siswa Miskin (BSM) di SMA Negeri 3 Tualang. Analisis ini dilakukan dengan menggunakan metode Technique for Order of Preference by Similarity to Ideal Solution (TOPSIS) berdasarkan kriteria-kriteria yang telah ditentukan.
        </p>
        Berikut adalah data calon penerima beasiswa BSM yang sudah dihitung menggunakan metode Technique for Order of Preference by Similarity to Ideal Solution (TOPSIS):
        <br>
        <br>
        <div class="table-responsive">
            <table id="dataTable" class="table table-bordered" width="100%" cellspacing="0">
                
                <!-- head -->
                <thead>
                    <tr>
                        <th>Nama</th>
                        <th>best_distance</th>
                        <th>worst_distance</th>
                        <th>worst_similarity</th>
                        <th>worst_similarity_rank</th>
                        <th>best_similarity</th>
                        <th>best_similarity_rank</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- row 1 -->
                    {% for d in data %}
                    <tr>
                        <th>{{ d.nama }}</th>
                        <td>{{ d.best_distance }}</td>
                        <td>{{ d.worst_distance }}</td>
                        <td>{{ d.worst_similarity }}</td>
                        <td>{{ d.worst_similarity_rank }}</td>
                        <td>{{ d.best_similarity }}</td>
                        <td>{{ d.best_similarity_rank }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="card-body">
            <p>Berikut siswa yang berhak menerima beasiswa BSM di SMA Negeri 3 Tualang:</p>
            <div class="table-responsive">
                <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Hasil yang didapatkan</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><i>Yang Berhak Menerima Beasiswa Bantuan Siswa Miskin di SMA Negeri 3 Tualang berdasarkan perhitungan metode topsis diatas adalah: </i></td>
                            {% for d in data|dictsort:"worst_similarity_rank"|slice:":3" %}
                                <tr>
                                    <td><strong>{{ d.nama }} - {{ d.worst_similarity_rank }}</strong></td>
                                </tr>
                            {% endfor %}
                        </tr>
                    </tbody>
                </table>

                <table width="100%">
                    <thead>
                        <tr>
                            <th>Demikian hasil analisis penerima beasiswa bantuan siswa miskin (BSM) di SMA Negeri 3 Tualang dan dapat dipergunakan sebagaimana mestinya.</th>
                        </tr>
                        <tr>
                            <td colspan="2"><br> <br></td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr style="text-align: end;">
                            <td>Perawang,&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;2024</td>
                            <!-- <td><br><br>Kepala Sekolah</td> -->
                            <td colspan="2"><br> <br> <br> <br> <br> <br><br><br><br><br><br><br></td>
                        </tr>
                       
                        <tr style="text-align: end;">
                            <td><strong><u>HERMAYANTI, S.PD</u></strong></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script>
        function cetakTabel() {
            var printContents = document.getElementById('printArea').innerHTML;
            var originalContents = document.body.innerHTML;

            document.body.innerHTML = printContents;

            window.print();

            document.body.innerHTML = originalContents;
        }
        function submitForm() {
            document.getElementById('filterForm').submit();
        }
    </script>

{% endblock %}

topsis/templates/index.html
{% extends 'base.html' %}

{% block content %}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <div class="row d-flex justify-content-between">
            <h6 class="m-0 font-weight-bold text-primary">Input Data</h6>
            <a class="btn btn-primary" style="float: right;" href="{% url 'input' %}">Add Data</a>
        </div>
    </div>
    <div class="card-body">
        <form id="filterForm" method="GET" action="{% url 'index' %}">
            <!-- Pilihan tahun -->
            <select name="year" id="year">
                {% for available_year in available_years %}
                    <option value="{{ available_year }}" {% if available_year == selected_year %}selected{% endif %}>{{ available_year }}</option>
                {% endfor %}
            </select>
            <button type="button" onclick="submitForm()">Filter</button>
        </form>

        <div class="table-responsive">
            <table id="dataTable" class="table table-bordered" width="100%" cellspacing="0">
                <!-- head -->
                <thead>
                    <tr>
                        {% for f in field_names %}
                            <th>{{ f }}</th>
                        {% endfor %}
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <!-- row 1 -->
                    {% for d in data %}
                        <tr>
                            <th>{{ d.id }}</th>
                            <td>{{ d.nama }}</td>
                            <td>{{ d.get_surat_keterangan_tidak_mampu_display }}</td>
                            <td>{{ d.get_kondisi_rumah_display }}</td>
                            <td>{{ d.get_keaktifan_ekstrakurikuler_display }}</td>
                            <td>{{ d.get_penghasilan_display }}</td>
                            <td>{{ d.get_tanggungan_display }}</td>
                            <td>{{ d.get_keterangan_display }}</td>
                            <td>{{ d.tahun }}</td>
                            <td>
                                <a href="{% url 'edit' d.id%}" class="btn btn-warning" onclick="return confirm('Are you sure edit?')"><i class="fa fa-edit"></i> </a> <a href="{% url 'topsis.delete' d.id %}"
                                    class="btn btn-danger" onclick="return confirm('Are you sure delete?')"><i
                                        class="far fa-trash-alt"></i> </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    function submitForm() {
        document.getElementById("filterForm").submit();
    }
</script>

{% endblock %}

topsis/templates/topsis_edit.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h2>Edit Data</h2>
    <hr>
    <form action="{% url 'topsis.update' category.id %}" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group row">
            <label for="{{ field.id_for_label }}" class="col-sm-4 col-form-label">{{ field.label }}</label>
            <div class="col-sm-8">
                {{ field }}
            </div>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-warning">Update</button>
    </form>
</div>
{% endblock %}